# Generated by Django 5.1 on 2024-08-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('type_room', models.CharField(max_length=200)),
                ('receptions', models.CharField(max_length=200)),
                ('floor', models.IntegerField()),
            ],
        ),
    ]
